### ISSUE TITLE
Charset error

### ISSUE THREAD

**Issue by TitovLab** [mbeijen/App-OTRS-CreateTicket#2]
Many thanks for your work and knowledge.
There are some errors with Russian characters in otrs.CreateTicket.pl
For example, if queue in OTRS named in Russian, otrs.CreateTicket.pl will not work.
If queue named in English, then ticket will be created, but OTRS create auto response in wrong charset:
![default](https://cloud.githubusercontent.com/assets/11898568/7214752/7ef95b02-e5c2-11e4-935f-76ce3d3a5e54.PNG)
I modified two lines in  otrs.CreateTicket.pl, after that all fine, but I am not a programmer and don't know Perl and newer work with SOAP. Maybe you can do it better?
Modified line in "for my $Element (@TicketFields)" and "for my $Element (@ArticleFields)":
my $Param = SOAP::Data->type("string")->name( $Element => $Param{$Element} );

**Comment by mbeijen** [comment]
Hi, thanks a lot for your bug report.

I was able to reproduce the issue using some Russian text.
I patched the otrs.CreateTicket.pl script to now force the attributes to string and put a new version on CPAN.

Kindest regards,

Michiel
