### ISSUE TITLE
PROXY ERROR

### ISSUE THREAD

**Issue by ghost** [mbeijen/App-OTRS-CreateTicket#6]
This script over Proxy is error. Who can i set the Proxysetting ?

**Comment by mbeijen** [comment]
Hi Dennis, you could probably use the HTTP_PROXY environment variable:

    HTTP_PROXY=proxy.example.corp otrs.CreateTicket.pl ....

or use `set HTTP_PROXY=proxy.example.corp` to set it in your shell.

**Comment by ghost** [comment]
I have set Proxy in Shell the error is constant


Von: Michiel Beijen [mailto:notifications@github.com]
Gesendet: Montag, 23. Oktober 2017 15:53
An: mbeijen/App-OTRS-CreateTicket <App-OTRS-CreateTicket@noreply.github.com>
Cc: Rupprecht Dennis <Dennis.Rupprecht@cancom.de>; Author <author@noreply.github.com>
Betreff: Re: [mbeijen/App-OTRS-CreateTicket] PROXY ERROR (#6)


Hi Dennis, you could probably use the HTTP_PROXY environment variable:

HTTP_PROXY=proxy.example.corp otrs.CreateTicket.pl ....

or use set HTTP_PROXY=proxy.example.corp to set it in your shell.

**Comment by mbeijen** [comment]
Well, what is the error message you get? What OS do you use? What version of LWP::UserAgent do you have installed?

**Comment by ghost** [comment]
This is a script in /etc/profile.d/proxy

export http_proxy="http://*\\*:*:3128"
export HTTP_PROXY=$http_proxy

pear config-set http_proxy 'http://*\\*:*@*:3128'


\\

With domainuser


OS= centos


Von: Michiel Beijen [mailto:notifications@github.com]
Gesendet: Montag, 23. Oktober 2017 15:53
An: mbeijen/App-OTRS-CreateTicket <App-OTRS-CreateTicket@noreply.github.com>
Cc: Rupprecht Dennis <Dennis.Rupprecht@cancom.de>; Author <author@noreply.github.com>
Betreff: Re: [mbeijen/App-OTRS-CreateTicket] PROXY ERROR (#6)


Hi Dennis, you could probably use the HTTP_PROXY environment variable:

HTTP_PROXY=proxy.example.corp otrs.CreateTicket.pl ....

or use set HTTP_PROXY=proxy.example.corp to set it in your shell.

**Comment by ghost** [comment]
The error is:

500 Can't connect to *:3128 (SSL connect attempt failed because of handshake problemserror:00000000:lib(0):func(0):reason(0)) at /usr/lib/nagios/plugins/otrs.CreateTicket.pl line 184.

Von: Michiel Beijen [mailto:notifications@github.com]
Gesendet: Montag, 23. Oktober 2017 15:56
An: mbeijen/App-OTRS-CreateTicket <App-OTRS-CreateTicket@noreply.github.com>
Cc: Rupprecht Dennis <Dennis.Rupprecht@cancom.de>; Author <author@noreply.github.com>
Betreff: Re: [mbeijen/App-OTRS-CreateTicket] PROXY ERROR (#6)


Well, what is the error message you get? What OS do you use? What version of LWP::UserAgent do you have installed?

**Comment by ghost** [comment]
Okay Problem was LWP::UserAgent


Thanks

Von: Michiel Beijen [mailto:notifications@github.com]
Gesendet: Montag, 23. Oktober 2017 15:56
An: mbeijen/App-OTRS-CreateTicket <App-OTRS-CreateTicket@noreply.github.com>
Cc: Rupprecht Dennis <Dennis.Rupprecht@cancom.de>; Author <author@noreply.github.com>
Betreff: Re: [mbeijen/App-OTRS-CreateTicket] PROXY ERROR (#6)


Well, what is the error message you get? What OS do you use? What version of LWP::UserAgent do you have installed?
